import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";

const OrderStyle = StyleSheet.create({
   MainContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    width: wp("100%"),
    // alignItems:"center",
    // justifyContent:"center",
    paddingBottom: hp("2%"),
  },
  container: {
    alignSelf: "center",
    width: wp("91.11%"),
    height: hp("18%"),
    backgroundColor: "#FFF",
    justifyContent: "space-between",
    // alignItems: "center",
    flexDirection: "row",
    borderRadius: 25,
    marginTop: 15,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#EDEDED",
    shadowColor: "#79797940",
  },
  Image: {
    width: wp("21.6%"),
    height: hp("10%"),
    borderRadius: 25,
    resizeMode: "contain",
    borderWidth: 1,
    borderColor: "#EDEDED",
    left: wp("5%"),
    top: hp("1.625%"),
    // backgroundColor: "#FFFFFF",
  },
  contentView: {
    width: wp("62.9%"),
    height: hp("18%"),
    // backgroundColor: "lightblue",
    // justifyContent: "space-between",
    // alignItems: "center",
    // flexDirection: "row",
    borderRadius: 25,
  },
  reOrder: {
    position: "absolute",
    width: wp("22.5%"),
    height: hp("4%"),
    borderWidth: 1,
    borderColor: "#1D9ADC",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    right: wp("5%"),
    top: hp("1.625%"),
  },
  reOrderText: {
    fontSize: RFValue(14, 800),
    fontWeight: "500",
    color: "#1D9ADC",
    fontFamily: "Poppins-Medium",
  },
  detailsView: {
    width: wp("62.9%"),
    height: hp("11.25%"),
    // backgroundColor: "orange",
    // justifyContent: "space-between",
    // alignItems: "center",
    // flexDirection: "row",
    paddingLeft: wp("5.28%"),
    // paddingVertical: 15,
    borderRadius: 25,
  },
  orderId: {
    fontSize: RFValue(14, 800),
    fontWeight: "500",
    color: "#525252",
    fontFamily: "Poppins-Medium",
    marginTop: hp("1.6%"),
    // backgroundColor:"#000",
    width: wp("26%"),
  },
  dateText: {
    fontSize: RFValue(12, 800),
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
    color: "#B5B5B5",
  },
  Amount: {
    fontSize: RFValue(12, 800),
    fontWeight: "500",
    color: "#525252",
    fontFamily: "Poppins-Medium",
    // lineHeight: 13,
  },
  buttonCommonView: {
    // backgroundColor:"#000",
    width: wp("55%"),
    height: hp("6%"),
    justifyContent: "space-between",
    // alignItems: "center",
    flexDirection: "row",
    // borderBottomLeftRadius: 25,
    // borderBottomRightRadius: 25,
    // paddingHorizontal: 16,
    position: "absolute",
    bottom: 0,
    right: wp("3.5%"),
  },
  quantityTouchable: {
    width: wp("91.11%"),
    height: hp("5%"),
    alignItems: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  gradientButton: {
    width: wp("91.11%"),
    height: hp("5%"),
    alignItems: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    // overflow: "hidden",
    // backgroundColor: "#000",
  },
  addToCartText: {
    color: "white",
    fontSize: RFValue(14, 800),
    fontFamily: "Poppins-SemiBold",
    fontWeight: "600",
  },
});

export default OrderStyle;
