import { StyleSheet, Dimensions } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import colors from "../../../config/colors";
import { RFValue } from "react-native-responsive-fontsize";
const screenWidth = Dimensions.get('window').width;
const isSmallScreen = screenWidth < 410;

const PaginationProductWithBrandStyle = StyleSheet.create({
  selectedCat: {
    backgroundColor: "#F4F9FF",
    borderRadius: 10,
    shadowColor: "#E4E4E4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    paddingHorizontal: wp("3.89%"),
  },
  selectedCatText: {
    color: "#525252",
    fontSize: RFValue(12),
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
  gradient: {
    flex: 1,
    width: wp("100%"),
    height: hp("100%"),
    alignSelf: "center",
  },
  catListCommonView: {
    backgroundColor: "#FFFFFF",
    width: wp("100%"),
    height: hp("6%"),
    marginTop: hp("0.875%"),
    marginBottom: hp("0.25%"),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    elevation: 3,
    shadowColor: "#A3A3A340",
  },
  filterIcon: {
    width: wp("9.72%"),
    height: hp("3.75%"),
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: wp("4.44%"),
    marginRight: wp("1.39%"),
  },
  catListView: {
    backgroundColor: "white",
    height: hp("3.75%"),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: wp("3.89%"),
    marginRight: wp("1.39%"),
    borderRadius: 10,
    borderColor: "#E4E4E4",
    borderWidth: wp("0.28%"),
  },
  catText: {
    color: "#525252",
    fontFamily: "Poppins-Medium",
    fontSize: RFValue(12),
    fontWeight: "500",
  },
  container: {
    flex: 1,
    width: wp("100%"),
    alignItems: "flex-start",
    justifyContent: "flex-start",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: 10,

  },
  flatList: {
    width: wp("91.11%"),
    alignItems: "flex-start",
    overflow: "hidden",
    paddingBottom: hp("20%"),
  },
  flatList2: {
    height: hp("6%"),
    paddingRight: wp("4%"),
    alignItems: "center",
    alignSelf: "center",
  },
  widget: {
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    marginVertical: hp("1%"),
    marginHorizontal: wp("1%"),
    width: wp("44%"),
    borderRadius: 12,
    elevation: 4,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    alignItems: "stretch",
    padding: wp('2%'),
    borderWidth: 1,
    borderColor: '#F0F0F0',
    // Height will be determined by content
  },
  imageTouchView: {
    width: '100%',
    aspectRatio: 1.33, // Makes it wider than tall (4:3 aspect ratio)
    maxHeight: wp('60%'), // Optional: prevent it from getting too tall on larger screens
    alignItems: 'center',
    justifyContent: 'center',
    padding: wp('2%'),
    backgroundColor: 'transparent',
    borderRadius: 8,
    marginBottom: hp('1%'),
    position: 'relative',
    overflow: 'hidden',
  },
  wishListButton: {
    position: "absolute",
    top: -8,
    right: -6,
    padding: wp('2%'),
    zIndex: 2,
  },
  wishicon: {
    resizeMode: "contain",
    width: wp("6%"),
    height: wp("6%"),
  },
  images: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    position: 'absolute',
  },
  imagePlaceholder: {
    height: 185,
    width: 180,
    backgroundColor: "#F4F9FF",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
  placeholderText: {
    color: "#666",
    fontSize: 14,
  },
  textView: {
    width: '100%',
    paddingHorizontal: wp('2%'),
    marginBottom: hp('1%'),
    flex: 1,
    justifyContent: 'space-between',
  },
  ProductNameView: {
    justifyContent: "center",
  },
  ProductName: {
    textAlign: "left",
    fontSize: RFValue(13, 800),
    fontWeight: "500",
    color: "#333333",
    fontFamily: "Poppins-Medium",
    marginBottom: hp('0.5%'),
    lineHeight: 18,
    height: 36,
    overflow: 'hidden',
  },
  PriceCommonView: {
    flexDirection: "row",
    alignItems: "baseline",
    alignSelf: "baseline",
  },
  PriceView: {
    justifyContent: "center",
  },
  AedText: {
    fontSize: RFValue(14, 800),
    textAlign: "left",
    fontWeight: "600",
    color: "#525252",
    fontFamily: "Poppins-SemiBold",
  },
  ProductPrice: {
    textAlign: "left",
    color: "#525252",
    fontSize: RFValue(14, 800),
    fontWeight: "600",
  },
  commonView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  oldPriceView: {
    flex: 1,
  },
  oldProductPrice: {
    fontSize: RFValue(14, 800),
    textDecorationLine: "line-through",
    color: "#FE5656",
    
  },
  quantitySection: {
    width: 80,
    alignItems: "flex-end",
  },
  addButton: {
    width: 27,
    height: 27,
    resizeMode: "contain",
  },
  errorContainer: {
    padding: 10,
    alignItems: "center",
    width: "100%",
  },
  errorText: {
    color: "#FE5656",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 5,
  },
  retryButton: {
    padding: 8,
    backgroundColor: colors.primary,
    borderRadius: 5,
    minWidth: 100,
    alignItems: "center",
  },
  retryText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  emptyContainer: {
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    width: "100%",
    paddingTop: hp("20%"),
  },
  noProductsImage: {
    width: wp('45.28%'),
    height: wp("45.28%"),
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
  },
  noProductsText: {
    fontSize: RFValue(14),
    marginTop: hp('2%'),
    color: "#525252",
    fontWeight: "500",
    textAlign: "center",
    fontFamily: "Poppins-Medium",
    overflow: "hidden",
  },
  loadingContainer: {
    width: wp("100%"),
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center"
  },
  loadingText: {
    marginTop: 10,
    color: "#B4B4B4",
    fontSize: RFValue(14, 800),
  },
  quantityTouchable: {
    width: '100%',
    height: hp('5.5%'),
    marginTop: hp('1%'),
    borderRadius: 8,
    overflow: 'hidden',
  },
  gradientButton: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    overflow: "hidden",
  },
  addToCartButton: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.primary,
  },
  addToCartText: {
    color: "white",
    fontSize: RFValue(14, 800),
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
  });

export default PaginationProductWithBrandStyle;
