import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import colors from "../../../config/colors";
import { RFValue } from "react-native-responsive-fontsize";

const ProductDetailsStyle = StyleSheet.create({
 container: {
   flex: 1,
   backgroundColor: "#FFFFFF",
 },
 scrollView: {
   flex: 1,
 },
 scrollContentContainer: {
   paddingBottom: 120,
 },
 skeletonImageContainer: {
   width: wp("91.11%"),
   height: hp("40%"),
   alignSelf: "center",
   borderRadius: 15,
   marginVertical: 17,
 },
 productImage: {
   width: wp("91.11%"),
   height: hp("40%"),
   resizeMode: "contain",
   alignSelf: "center",
   backgroundColor: "#F6F9FF",
   borderRadius: 15,
   marginTop: 17,
 },
 wishlistButton: {
   position: "absolute",
   right: 45,
   top: 35,
 },
 wishlistIcon: {
   resizeMode: "contain",
   width: 30,
   height: 30,
 },
 productDetailsContainer: {
   marginHorizontal: 25,
   alignItems: "flex-start",
 },
 stockText: {
   fontSize: 15,
   fontWeight: "500",
   lineHeight: 50,
 },
 productNameText: {
   fontSize: 23,
   fontWeight: "700",
   color: "#133051",
 },
 packSizeText: {
   fontSize: 18,
   fontWeight: "500",
   lineHeight: 40,
   color: "rgba(37,37,37,0.65)",
 },
 priceText: {
   fontSize: 24,
   fontWeight: "700",
   lineHeight: 45,
   color: "#133051",
 },
 tableScrollView: {
   marginBottom: 12,
 },
 ProductImage: {
   resizeMode: "contain",
   width: 200,
   height: 200,
 },
 flatList: {
   overflow: "hidden",
 },
 imageTouchView: {
   backgroundColor: "#F4F9FF",
   borderRadius: 15,
   height: 145,
   width: 145,
   resizeMode: "contain",
   alignItems: "center",
   justifyContent: "center",
   overflow: "hidden",
 },
 images: {
   height: 145,
   width: 145,
   resizeMode: "contain",
   backgroundColor: "#F4F9FF",
   borderRadius: 15,
 },
 textView: {
   height: 75,
   width: 145,
   flexDirection: "column",
 },
 ProductNameView: {
   width: "100%",
   height: "55%",
   overflow: "hidden",
 },

 commonViewDetails: {
   flexDirection: "row",
   alignItems: "center",
   marginBottom: hp("1%"),
   flexWrap: "wrap",
 },
 badgeContainer: {
   flexDirection: "row",
   flexWrap: "wrap",
   gap: 8,
   flex: 1,
 },
 categoryBadge: {
   backgroundColor: "#E8F5E9",
   borderRadius: 12,
   paddingHorizontal: wp("3%"),
   paddingVertical: hp("0.5%"),
   marginRight: wp("1%"),
   marginBottom: hp("0.5%"),
   borderWidth: 1,
   borderColor: "#68B054",
 },
 badgeText: {
   fontSize: RFValue(12, 800),
   fontFamily: "Poppins-Regular",
   color: "#68B054",
   fontWeight: "500",
 },
 brandBadge: {
   backgroundColor: "#E3F2FD",
   borderRadius: 12,
   paddingHorizontal: wp("3%"),
   paddingVertical: hp("0.5%"),
   borderWidth: 1,
   borderColor: "#133051",
 },
 brandBadgeText: {
   fontSize: RFValue(13, 800),
   fontFamily: "Poppins-Medium",
   color: "#133051",
   fontWeight: "600",
 },
 detailsText1: {
   fontSize: RFValue(16, 800),
   fontFamily: "Poppins-Medium",
   color: "#252525",
   fontWeight: "500",
   marginRight: wp("2%"),
 },
 detailsText2: {
   fontSize: RFValue(14, 800),
   fontFamily: "Poppins-Regular",
   color: "#525252",
   fontWeight: "500",
 },
 ProductName: {
   alignItems: "center",
   textAlign: "left",
   bottom: -5,
   fontSize: 16,
   color: "#252525",
 },
 PriceView: {
   width: "100%",
   alignItems: "center",
   height: "25%",
   overflow: "hidden",
   flexDirection: "row",
 },
 ProductPrice: {
   alignItems: "center",
   fontSize: 16,
   fontWeight: "600",
   color: "#133051",
 },
 commonView: {
   flexDirection: "row",
   justifyContent: "space-between",
   width: "100%",
   height: "20%",
 },
 oldPriceView: {
   width: "50%",
   // alignItems:'center',
   height: "100%",
   overflow: "hidden",
   flexDirection: "row",
   justifyContent: "flex-start",
 },
 oldProductPrice: {
   fontSize: 11,
   // fontWeight: "600",
   alignItems: "center",
   textDecorationLine: "line-through",
   textDecorationColor: "#FE5656",
   color: "#FE5656",
 },
 quantitySection: {
   width: "50%",
   height: "100%",
   alignItems: "flex-end",
   position: "absolute",
   right: 0,
   bottom: 15,
 },
 dropdownDescriptionContent: {
   flexDirection: "column",
   marginBottom: hp("1.875%"),
   width: wp("91.1%"),
   paddingVertical: hp("1.875%"),
   alignSelf: "center",
   alignItems: "flex-start",
   justifyContent: "space-between",
 },
 ButtonView: {
   backgroundColor: "#58BB47",
   width: "89%",
   height: "7.5%",
   alignSelf: "center",
   position: "absolute",
   bottom: 35,
   borderRadius: 15,
   justifyContent: "center",
 },
 buttonText: {
   textAlign: "center",
   color: "#FFFFFF",
   fontSize: 20,
   fontWeight: 500,
 },
 commonTextSpec: {
   fontSize: 17,
   fontWeight: "500",
   lineHeight: 26,
   color: "#000",
 },
 commonViewSpec: {
   flexDirection: "row",
   alignItems: "baseline",
   width: "100%",
   flexWrap: "wrap",
 },
 commonTextSpec2: {
   fontSize: 15,
   fontWeight: "500",
   color: "#000",
   flexShrink: 1,
 },
 Dot: {
   fontSize: 35,
   fontWeight: "900",
   color: "#000",
 },
 ListOuterView: {
   backgroundColor: "#FFFFFF",
   marginVertical: 5,
   width: "100%",
   height: 75,
   alignSelf: "center",
   borderRadius: 15,
   borderWidth: 0.4,
   borderColor: "rgba(37,37,37,0.25)",
   justifyContent: "space-between",
   flexDirection: "row",
 },
 ImageView: {
   backgroundColor: "#FFFFFF",
   width: "23%",
   height: "100%",
   justifyContent: "center",
   alignItems: "center",
   borderRadius: 15,
   overflow: "hidden",
 },
 DetailsView: {
   paddingVertical: 15,
   width: "62%",
   height: "100%",
   borderRadius: 15,
   flexDirection: "row",
   justifyContent: "space-between",
 },
 ProductDetailsView: {
   width: "80%",
   height: "100%",
   borderRadius: 20,
   justifyContent: "center",
   paddingLeft: 15,
 },
 nameText: {
   fontSize: 17,
   fontWeight: 600,
   color: "#252525",
 },
 weightText: {
   fontSize: 17,
   fontWeight: 600,
   color: "#B5B5B5",
 },
 rateText: {
   fontSize: 18,
   fontWeight: 600,
   color: "#133051",
 },
 TickView: {
   width: "15%",
   height: "100%",
   justifyContent: "center",
   alignItems: "center",
   borderRadius: 15,
   overflow: "hidden",
 },
  });

export default ProductDetailsStyle;
