const appSettings = {
  almadina: {
    Client: "almadina",
    FUSName: "Almadina AUH",
    FUSDescription:
      " The current version of the application is no longer supported. We apologize for any inconvenience we may have caused to you.",
    AppVersion: "8.8.6",
    ClientUrl: "www.almadinahypermarket.ae",
    instagram: "www.instagram.com/almadinaabudhabi",
    facebook: "www.facebook.com/almadinahypermarket",
    whatsapp: "+971523431264",
    playstoreURL:
      "https://play.google.com/store/apps/details?id=com.almadinahypermarket.mobileapp",
    appStoreURL: "",
    mail: "",
    DefaultCurrency: "AED",
    PageID: 1,
    ContactPageId: 14,
    TermsIDEn: 5,
    TermsIDAr: 7,
    mapModal_AddressBox_ScrollList: true,
    profileSectionDrawer: true,
    category_Search: true,
    ShortMap: true,
    AutoTag: true,
    IsShippingAddress: true,
    showRemoveButton: true,
    CartReOrderStructure: true,
    InvertProductList: true,
    customBannerStyle: true,
    showtitle: true,
    SuggestionProducts : true,
    ShopByCategoryText: "shop_by_category",
    MainCategoryWidgetNOC: 4,
    DrawerWidth: "75%",
    drawerPosition: "right",
    drawerType: "front",
    AddressFields: [
      "firstName",
      "lastName",
      "telephone",
      "location",
      "address",
      "buildingNo",
      "road",
      "landMark",
    ],
    Text: {
      ClientNameKey: "clients.almadina", //client Name comes From ar or en json
    },
    fieldMessage: {
      firstName: "Enter your First Name.",
      lastName: "Enter your Last Name.",
      landMark: "Please enter your Landmark.",
      telephone: "Enter your Mobile Number.",
      telephone2: "Enter your Secondary Mobile Number.",
      buildingNo: "Enter your Building/Villa Number.",
      road: "Enter your Road/Block.",
      location: "Auto-tag or pick your Location.",
      address: "Enter your Address.",
    },
    screens: {
      Splash_screen: "ImageSplash",
      Welcome_screen: "IconWithBackground",
      Login_screen: "LoginWithBackgroundImage",
      Otp_screen: "BgImageWithOtp",
      SignUp_screen: "SignUpWithBackgroundImage",
      Category_screen: "NormalCategory",
      Cart_screen: "CartWithHorizontalSlideProductsList",
      Checkout_screen: "NormalCheckout",
      Account_screen: "SimpleAccount",
      Address_screen: "AddressWithMapModal",
      AddressSwitch_screen: "NormalAddressSwitch",
      Booklets_screen: "NormalBooklets",
      Notification_screen: "NormalNotification",
      OrderDetails_screen: "NormalOrderDetails",
      Order_screen: "NormalOrder",
      OrderSuccessScreen_screen: "NormalOrderSuccess",
      ProductDetails_screen: "NormalProductDetails",
      ProductListing_screen: "PaginationProductListing",
      TrackOrder_screen: "NormalTrackOrder",
      Wishlist_screen: "NormalWishlist",
      CustomTextInput: "IconWithTextInput",
      CustomTabBar: "NormalTabBar",
      Home_Header: "BgHomeHeader",
      search_bar: "Search_with_cam",
      ReOrder_screen: "NormalReOrder",
      Search_screen: "NormalSearch",
      Profile_screen: "SimpleProfile",
      FAQs_screen: "CustomFAQs",
    },
  },
  almadinadot: {
    Client: "almadinadot",
    FUSName: "Dot AE",
    FUSDescription:
      " The current version of the application is no longer supported. We apologize for any inconvenience we may have caused to you.",
    AppVersion: "4.0.6",
    ClientUrl: "www.almadinahypermarket.ae",
    instagram: "www.instagram.com/almadinaabudhabi",
    facebook: "www.facebook.com/almadinahypermarket",
    whatsapp: "+971523431264",
    playstoreURL:
      "https://play.google.com/store/apps/details?id=com.almadinadxb.online",
    appStoreURL: "",
    mail: "",
    DefaultCurrency: "AED",
    PageID: 1,
    ContactPageId: 14,
    mapModal_AddressBox_ScrollList: true,
    profileSectionDrawer: true,
    profileSectionDrawerImage: true,
    category_Search: true,
    ShortMap: true,
    AutoTag: true,
    SearchFirstLayout: true,
    TermsIDEn: 5,
    TermsIDAr: 7,
    SearchPanel: true,
    IsShippingAddress: true,
    hideFooter: true,
    CartReOrderStructure: true,
    hideProductName: true,
    conditionalHeaderProps: true,
    showRemoveButton: true,
    customcolor: true,
    ShopByCategoryText: "",
    backgroundColor:"#12a14f",
    MainCategoryWidgetNOC: 3,
    DrawerWidth: "82%",
    DrawerLeftRadius: true,
    drawerPosition: "right",
    drawerType: "front",
    AddressFields: [
      "firstName",
      "lastName",
      "landMark",
      "telephone",
      "buildingNo",
      "road",
      "location",
      "address",
    ],
    fieldMessage: {
      firstName: "Enter your First Name.",
      lastName: "Enter your Last Name.",
      landMark: "Please enter your Landmark.",
      telephone: "Enter your Mobile Number.",
      telephone2: "Enter your Secondary Mobile Number.",
      buildingNo: "Enter your Building/Villa Number.",
      road: "Enter your Road/Block.",
      location: "Auto-tag or pick your Location.",
      address: "Enter your Address.",
    },
    Text: {
      ClientName: "DOT AE",
    },
    screens: {
      Splash_screen: "VideoSplash",
      Welcome_screen: "IconWithBackground",
      Login_screen: "LoginWithBackgroundImage",
      Otp_screen: "BgImageWithOtp",
      SignUp_screen: "SignUpWithBackgroundImage",
      Category_screen: "LeftSIdeCategory",
      Cart_screen: "CartWithHorizontalSlideProductsList",
      Checkout_screen: "NormalCheckout",
      Account_screen: "NormalAccount",
      Address_screen: "AddressWithMapModal",
      AddressSwitch_screen: "NormalAddressSwitch",
      Booklets_screen: "NormalBooklets",
      Notification_screen: "NormalNotification",
      OrderDetails_screen: "SubstitutionOrderDetails",
      Order_screen: "NormalOrder",
      OrderSuccessScreen_screen: "NormalOrderSuccess",
      ProductDetails_screen: "NormalProductDetails",
      ProductListing_screen: "PaginationProductListing",
      TrackOrder_screen: "NormalTrackOrder",
      Wishlist_screen: "NormalWishlist",
      CustomTextInput: "IconWithTextInput",
      CustomTabBar: "NormalTabBar",
      Home_Header: "NormalHomeHeader",
      search_bar: "Search_with_without_scan",
      ReOrder_screen: "NormalReOrder",
      Search_screen: "NormalSearch",
      Profile_screen: "UnderConstruction",
      FAQs_screen: "CustomFAQs",
    },
  },
  foodworld: {
    Client: "foodworld",
    FUSName: "Foodworld",
    FUSDescription:
      " The current version of the application is no longer supported. We apologize for any inconvenience we may have caused to you.",
    AppVersion: "1.0.0",
    ClientUrl: "",
    instagram: "www.instagram.com/foodworld",
    facebook: "www.facebook.com/fodworld",
    whatsapp: "",
    playstoreURL:
      "https://play.google.com/store/apps/details?id=com.foodworld.mobileapp",
    appStoreURL: "",
    mail: "",
    DefaultCurrency: "BHD",
    mapModal_AddressBox_ScrollList: true,
    category_Search: true,
    ShortMap: true,
    ContactPageId: 12,
    AutoTag: true,
    // Order_ReorderButton: true,
    MainCategoryWidgetNOC: 4,
    DrawerWidth: "75%",
    ShopByCategoryText: "shop_by_category",
    drawerPosition: "left",
    drawerType: "front",
    AddressFields: [
      "firstName",
      "lastName",
      "landMark",
      "telephone",
      "buildingNo",
      "road",
      "location",
      "address",
    ],
    Text: {
      ClientName: "FoodWorld",
    },
    fieldMessage: {
      firstName: "Enter your First Name.",
      lastName: "Enter your Last Name.",
      landMark: "Please enter your Landmark.",
      telephone: "Enter your Mobile Number.",
      telephone2: "Enter your Secondary Mobile Number.",
      buildingNo: "Enter your Building/Villa Number.",
      road: "Enter your Road/Block.",
      location: "Auto-tag or pick your Location.",
      address: "Enter your Address.",
    },
    screens: {
      Splash_screen: "VideoSplash",
      Welcome_screen: "IconWithOutBackground",
      Login_screen: "LoginWithOutBackgroundImage",
      Otp_screen: "NormalOtp",
      SignUp_screen: "SignUpWithOutBackgroundImage",
      Category_screen: "NormalCategory",
      Cart_screen: "CartWithSummaryCardAndWidget",
      Checkout_screen: "NormalCheckout",
      Account_screen: "NormalAccount",
      Address_screen: "AddressWithMapModal",
      AddressSwitch_screen: "NormalAddressSwitch",
      Booklets_screen: "NormalBooklets",
      Notification_screen: "NormalNotification",
      OrderDetails_screen: "SubstitutionOrderDetails",
      Order_screen: "NormalOrder",
      OrderSuccessScreen_screen: "NormalOrderSuccess",
      ProductDetails_screen: "NormalProductDetails",
      ProductListing_screen: "PaginationProductListing",
      TrackOrder_screen: "NormalTrackOrder",
      Wishlist_screen: "NormalWishlist",
      CustomTextInput: "NormalTextInput",
      CustomTabBar: "NormalTabBar",
      Home_Header: "NormalHomeHeader",
      search_bar: "Search_with_without_scan",
      ReOrder_screen: "NormalReOrder",
      Search_screen: "NormalSearch",
      Profile_screen: "UnderConstruction",
      FAQs_screen: "CustomFAQs",
    },
  },
  benchmarkfoods: {
    Client: "benchmarkfoods",
    FUSName: "Benchmarkfoods",
    FUSDescription:
      " The current version of the application is no longer supported. We apologize for any inconvenience we may have caused to you.",
    AppVersion: "1.0.0",
    ClientUrl: "",
    instagram: "www.instagram.com/benchmarkfoodsuae",
    facebook: "www.facebook.com/benchmarkfoodsuae",
    whatsapp: "+971506481495",
    playstoreURL: "",
    appStoreURL: "",
    mail: "rahiman@benchmarkfoods.ae",
    DefaultCurrency: "AED",
    BlockNewUser: true,
    Side_menu_App_icon: true,
    IsShippingAddress: true,
    AddAddressButton: true,
    cartOfferProduct: false,
    ContactPageId: 12,
    Gradient: true,
    MainCategoryWidgetNOC: 4,
    DrawerWidth: "75%",
    // category_Search: true,
    product_Search: true,
    Order_ReorderButton: true,
    socialmedia_login: false,
    mapModal_AddressBox_Normal: true,
    drawerPosition: "left",
    drawerType: "front",
    ShopByCategoryText: "shop_by_category",
    AddressFields: ["firstName", "location", "telephone"],
    fieldMessage: {
      firstName: "Enter your First Name.",
      telephone: "Enter your Mobile Number.",
      location: "Enter your Address.",
    },
    Text: {
      ClientName: "Benchmarkfoods",
    },
    screens: {
      Splash_screen: null,
      Welcome_screen: null,
      Login_screen: "LoginWithEmailAndPassword",
      Otp_screen: "NormalOtp",
      SignUp_screen: null,
      Category_screen: "SimpleCategory",
      Cart_screen: "CartWithSummaryCard",
      Checkout_screen: "NormalCheckout",
      Account_screen: "NormalAccount",
      Address_screen: "AddressWithMapModal",
      AddressSwitch_screen: "NormalAddressSwitch",
      Booklets_screen: "UnderConstruction",
      Notification_screen: "UnderConstruction",
      OrderDetails_screen: "SimpleOrderDetails",
      Order_screen: "GroupingOrder",
      OrderSuccessScreen_screen: "NormalOrderSuccess",
      ProductDetails_screen: "GradientProductDetails",
      ProductListing_screen: "PaginationProductListing",
      TrackOrder_screen: "UnderConstruction",
      Wishlist_screen: "NormalWishlist",
      CustomTextInput: "BorderNameTextInput",
      CustomTabBar: "NormalTabBar",
      Home_Header: "NormalHomeHeader",
      search_bar: "Search_with_cam",
      ReOrder_screen: "NormalReOrder",
      Search_screen: "NormalSearch",
      Profile_screen: "NormalProfile",
      FAQs_screen: "NormalFAQs",
    },
  },
  comtone: {
    Client: "comtone",
    FUSName: "comtone",
    FUSDescription:
      " The current version of the application is no longer supported. We apologize for any inconvenience we may have caused to you.",
    AppVersion: "3.1.4",
    ClientUrl: "www.almadinahypermarket.ae",
    instagram: "www.instagram.com/almadinaabudhabi",
    facebook: "www.facebook.com/almadinahypermarket",
    whatsapp: "+971523431264",
    playstoreURL: "https://play.google.com/store/apps/details?id=com.comtone.mobileapp",    
    appStoreURL: "",
    mail: "",
    DefaultCurrency: "AED",
    PageID: 1,
    mapModal_AddressBox_ScrollList: true,
    profileSectionDrawer: true,
    profileSectionDrawerImage: true,
    category_Search: true,
    ShortMap: true,
    AutoTag: true,
    SearchFirstLayout: true,
    SearchPanel: true,
    IsShippingAddress: true,
    hideFooter: true,
    customhideHeader: true,
    CartReOrderStructure: true,
    hideProductName: true,
    conditionalHeaderProps: true,
    showRemoveButton: true,
    ShopByCategoryText: "shop_by_category", 
    backgroundColor:"#164998",
    MainCategoryWidgetNOC: 3,
    DrawerWidth: "82%",
    DrawerLeftRadius: true,
    drawerPosition: "right",
    drawerType: "front",
    AddressFields: [
      "firstName",
      "lastName",
      "landMark",
      "telephone",
      "buildingNo",
      "road",
      "location",
      "address",
    ],
    fieldMessage: {
      firstName: "Enter your First Name.",
      lastName: "Enter your Last Name.",
      landMark: "Please enter your Landmark.",
      telephone: "Enter your Mobile Number.",
      telephone2: "Enter your Secondary Mobile Number.",
      buildingNo: "Enter your Building/Villa Number.",
      road: "Enter your Road/Block.",
      location: "Auto-tag or pick your Location.",
      address: "Enter your Address.",
    },
    Text: {
      ClientName: "DOT AE",
    },
    screens: {
      Splash_screen: "VideoSplash",
      Welcome_screen: "IconWithBackground",
      Login_screen: "LoginWithBackgroundImage",
      Otp_screen: "BgImageWithOtp",
      SignUp_screen: "SignUpWithBackgroundImage",
      Category_screen: "LeftSIdeCategory",
      Cart_screen: "CartWithHorizontalSlideProductsList",
      Checkout_screen: "NormalCheckout",
      Account_screen: "NormalAccount",
      Address_screen: "AddressWithMapModal",
      AddressSwitch_screen: "NormalAddressSwitch",
      Booklets_screen: "NormalBooklets",
      Notification_screen: "NormalNotification",
      OrderDetails_screen: "SubstitutionOrderDetails",
      Order_screen: "NormalOrder",
      OrderSuccessScreen_screen: "NormalOrderSuccess",
      ProductDetails_screen: "NormalProductDetails",
      ProductListing_screen: "PaginationProductListing",
      TrackOrder_screen: "NormalTrackOrder",
      Wishlist_screen: "NormalWishlist",
      CustomTextInput: "IconWithTextInput",
      CustomTabBar: "NormalTabBar",
      Home_Header: "BgHomeHeader",
      search_bar: "Search_with_cam",
      ReOrder_screen: "NormalReOrder",
      Search_screen: "NormalSearch",
      Profile_screen: "UnderConstruction",
      FAQs_screen: "CustomFAQs",
    },
  },
};

export default appSettings;
