import { StyleSheet, Dimensions } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import colors from "../../../config/colors";
import { RFValue } from "react-native-responsive-fontsize";
const screenWidth = Dimensions.get('window').width;
const isSmallScreen = screenWidth < 410;
const productListingStyle = StyleSheet.create({
  selectedCat: {
    backgroundColor: "#f5f7ff", // light highlight color (change as needed)
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3, // Android shadow
  },
  selectedCatText: {
    color: colors.primary, // use your theme color for text
    fontWeight: "bold",
  },
  catListCommonView: {
    backgroundColor: "#FFFFFF",
    width: wp("100%"),
    height: hp("6%"),
    marginTop: hp("0.875%"),
    marginBottom: hp("0.25%"),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    elevation: 3,
    shadowColor: "#A3A3A340",
  },
  filterIcon: {
    width: wp("9.72%"),
    height: hp("3.75%"),
    resizeMode: "contain",
    // borderRadius: wp('2%'),
    alignItems: "center",
    justifyContent: "center",
    marginLeft: wp("4.44%"),
    marginRight: wp("1.39%"),
  },
  catListView: {
    backgroundColor: "white",
    // width: "20%",
    height: hp("3.75%"),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: wp("3.89%"),
    marginRight: wp("1.39%"),
    borderRadius: 10,
    // elevation: 5,
    borderColor: "#E4E4E4",
    borderWidth: wp("0.28%"),
  },
  catText: {
    fontFamily: "Poppins-Medium",
    fontSize: RFValue(12),
    fontWeight: "500",
  },
  flatList2: {
    width: wp("100%"),
    height: hp("6%"),
    // backgroundColor: "#000",
    // paddingBottom: 15,
    alignItems: "center",
    // justifyContent: "center",
    alignSelf: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    width: "100%",
    alignItems: "center",
    paddingBottom: 20,
  },
  flatList: {
    width: "100%",
    paddingHorizontal: 16,
    paddingBottom: 100,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  widget: {
    marginVertical: 8,
    marginHorizontal: 6,
    height: 330,
    width: 170,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    alignItems: "center",
    alignSelf: 'flex-start',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: "hidden",
  },
  wishicon: {
    resizeMode: "contain",
    width: 25,
    height: 25,
  },
  imageTouchView: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    height: 170,
    width: 170,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 8,
  },
  images: {
    height: 170,
    width: 170,
    resizeMode: "cover",
    borderRadius: 12,
  },
  imagePlaceholder: {
    height: 170,
    width: 170,
    backgroundColor: "#F8F9FA",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  placeholderText: {
    color: "#666",
    fontSize: 14,
  },
  textView: {
    height: 100,
    width: 170,
    paddingHorizontal: 8,
    justifyContent: "space-between",
  },
  ProductNameView: {
    height: 47,
    justifyContent: "center",
  },
  ProductName: {
    fontSize: 14,
    color: "#252525",
    fontWeight: "500",
    lineHeight: 18,
  },
  PriceView: {
    height: 25,
    justifyContent: "center",
  },
  ProductPrice: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.green,
  },
  commonView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 35,
    width: "100%",
  },
  oldPriceView: {
    flex: 1,
  },
  oldProductPrice: {
    fontSize: 12,
    textDecorationLine: "line-through",
    color: "#FE5656",
  },
  quantitySection: {
    width: 125,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  addButton: {
    width: 27,
    height: 27,
    resizeMode: "contain",
  },
  errorContainer: {
    padding: 10,
    alignItems: "center",
    width: "100%",
  },
  errorText: {
    color: "#FE5656",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 5,
  },
  retryButton: {
    padding: 8,
    backgroundColor: colors.green,
    borderRadius: 5,
    minWidth: 100,
    alignItems: "center",
  },
  retryText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  emptyContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 24,
    backgroundColor: '#fff',
    borderRadius: 18,
    marginVertical: 40,
    marginHorizontal: 24,
    borderWidth: 1,
    borderColor: '#E4E4E4',
    shadowColor: '#A3A3A3',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 2,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    marginBottom: 18,
    resizeMode: 'contain',
    opacity: 0.7,
  },
  noProductsText: {
    fontSize: 20,
    color: '#525252',
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 8,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 6,
  },
  emptySubText: {
    fontSize: 15,
    color: '#A3A3A3',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    marginTop: 2,
    marginBottom: 2,
    lineHeight: 22,
  },
  loadingContainer: {
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 10,
    color: colors.green,
    fontSize: 14,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    marginVertical: 32,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E4E4E4',
    shadowColor: '#A3A3A3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  emptyText: {
    fontSize: RFValue(14),
    fontWeight: "600",
    // lineHeight: 50,
    // left: 14,
    color: "#3D3D3D99",
    fontFamily: "Poppins-Regular",
  },
  emptyText2: {
    fontSize: RFValue(11),
    fontWeight: "600",
    bottom: hp("0.5"),
    // left: 14,
    color: "#B2B2B2",
    fontFamily: "Poppins-Regular",
  },
  EmptyImage: {
    resizeMode: "contain",
    width: wp("15.28%"),
    height: hp("6.875%"),
    marginBottom: hp("1"),
  },
  ShopButton: {
    marginTop: hp("2.5"),
    backgroundColor: "#FFFFFF",
    width: wp("43%"),
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
  },
  gradientButton2: {
    width: wp("43%"),
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    overflow: "hidden",
  },
  shopButtonGradient: {
    width: wp("43%"),
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    // paddingHorizontal: 26,
    marginBottom: 7,
    borderRadius: 10,
    // backgroundColor: colors.green,
  },
});

export default productListingStyle;
