
const client = process.env.CLIENT;
const drawer = {
  almadina: [
    {
      itemId: 0,
      itemName: "home",
      navigateTo: "Home",
      iconType: "FontAwesome5",
      iconName: "home",
    },
    {
      itemId: 1,
      itemName: "my_account",
      navigateTo: "Account",
      iconType: "FontAwesome5",
      iconName: "user-circle",
    },
    {
      itemId: 2,
      itemName: "shop_by_category",
      navigateTo: "Category",
      iconType: "MaterialIcons",
      iconName: "category",
    },
    {
      itemId: 3,
      itemName: "promotions",
      navigateTo: "Promotions",
      iconType: "MaterialIcons",
      iconName: "local-offer",
    },
    {
      itemId: 4,
      itemName: "orders",
      navigateTo: "Order",
      iconType: "MaterialIcons",
      iconName: "shopping-bag",
    },
    {
      itemId: 5,
      itemName: "my_wish_list",
      navigateTo: "Wishlist",
      iconType: "FontAwesome5",
      iconName: "heart",
    },
    {
      itemId: 6,
      itemName: "my_wallet",
      navigateTo: "MyWallet",
      iconType: "FontAwesome5",
      iconName: "wallet",
    },
    {
      itemId: 7,
      itemName: "refer_your_friend",
      navigateTo: "Referral",
      iconType: "FontAwesome5",
      iconName: "user-plus",
    },
    {
      itemId: 8,
      itemName: "notifications",
      navigateTo: "Notification",
      iconType: "FontAwesome5",
      iconName: "bell",
    },
    {
      itemId: 9,
      itemName: "language_settings",
      navigateTo: "Welcome",
      iconType: "FontAwesome5",
      iconName: "language",
    },
     {
      itemId: 10,
      itemName: "terms_and_conditions",
      navigateTo: "TermsAndConditions",
      iconType: "FontAwesome5",
      iconName: "file-contract",
    },
    {
      itemId: 11,
      itemName: "about_us",
      navigateTo: "AboutUs",
      iconType: "FontAwesome5",
      iconName: "info-circle",
    },
    {
      itemId: 12,
      itemName: "contact_us",
      navigateTo: "ContactUs",
      iconType: "MaterialIcons",
      iconName: "contact-support",
    },
    {
      itemId: 13,
      itemName: "faqs",
      navigateTo: "FAQs",
      iconType: "FontAwesome5",
      iconName: "question-circle",
    },
    {
      itemId: 14,
      itemName: "complaints_suggestions",
      navigateTo: "Complaints",
      iconType: "MaterialIcons",
      iconName: "feedback",
    },
    {
      itemId: 15,
      itemName: "product_suggestions",
      navigateTo: "ProductSuggestions",
      iconType: "MaterialIcons",
      iconName: "lightbulb",
    },
    {
      itemId: 16,
      itemName: "signing_out",
      navigateTo: "SignOut",
      iconType: "MaterialIcons",
      iconName: "logout",
    },
    {
      itemId: 17,
      itemName: "change_your_number",
      navigateTo: "ChangeNumber",
      iconType: "FontAwesome5",
      iconName: "phone-alt",
    },
    {
      itemId: 18,
      itemName: "delete_account",
      navigateTo: "DeleteAccount",
      iconType: "MaterialIcons",
      iconName: "delete-forever",
    },
  ],
  almadinadot: [
    {
      itemId: 0,
      itemName: "home",
      navigateTo: "Home",
      iconType: "FontAwesome5",
      iconName: "home",
    },
    {
      itemId: 1,
      itemName: "my_account",
      navigateTo: "Account",
      iconType: "FontAwesome5",
      iconName: "user-circle",
    },
    {
      itemId: 2,
      itemName: "shop_by_category",
      navigateTo: "Category",
      iconType: "MaterialIcons",
      iconName: "category",
    },
    {
      itemId: 3,
      itemName: "promotions",
      navigateTo: "Promotions",
      iconType: "MaterialIcons",
      iconName: "local-offer",
    },
    {
      itemId: 4,
      itemName: "orders",
      navigateTo: "Order",
      iconType: "MaterialIcons",
      iconName: "shopping-bag",
    },
    {
      itemId: 5,
      itemName: "my_wish_list",
      navigateTo: "Wishlist",
      iconType: "FontAwesome5",
      iconName: "heart",
    },
    // {
    //   itemId: 6,
    //   itemName: "my_wallet",
    //   navigateTo: "Cart",
    //   iconType: "FontAwesome5",
    //   iconName: "wallet",
    // },
    // {
    //   itemId: 7,
    //   itemName: "refer_your_friend",
    //   navigateTo: "Referral",
    //   iconType: "FontAwesome5",
    //   iconName: "user-plus",
    // },
    {
      itemId: 8,
      itemName: "notifications",
      navigateTo: "Notification",
      iconType: "FontAwesome5",
      iconName: "bell",
    },
    {
      itemId: 9,
      itemName: "terms_and_conditions",
      navigateTo: "TermsAndConditions",
      iconType: "FontAwesome5",
      iconName: "file-contract",
    },
    {
      itemId: 10,
      itemName: "about_us",
      navigateTo: "AboutUs",
      iconType: "FontAwesome5",
      iconName: "info-circle",
    },
    {
      itemId: 11,
      itemName: "contact_us",
      navigateTo: "ContactUs",
      iconType: "MaterialIcons",
      iconName: "contact-support",
    },
    {
      itemId: 12,
      itemName: "faqs",
      navigateTo: "FAQs",
      iconType: "FontAwesome5",
      iconName: "question-circle",
    },
    {
      itemId: 13,
      itemName: "complaints_suggestions",
      navigateTo: "Complaints",
      iconType: "MaterialIcons",
      iconName: "feedback",
    },
    {
      itemId: 14,
      itemName: "product_suggestions",
      navigateTo: "ProductSuggestions",
      iconType: "MaterialIcons",
      iconName: "lightbulb",
    },
    {
      itemId: 15,
      itemName: "signing_out",
      navigateTo: "SignOut",
      iconType: "MaterialIcons",
      iconName: "logout",
    },
    {
      itemId: 16,
      itemName: "change_your_number",
      navigateTo: "ChangeNumber",
      iconType: "FontAwesome5",
      iconName: "phone-alt",
    },
    {
      itemId: 17,
      itemName: "delete_account",
      navigateTo: "DeleteAccount",
      iconType: "MaterialIcons",
      iconName: "delete-forever",
    },
  ],
  foodworld: {},
  benchmarkfoods: {},
};

export default drawer;
