import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import colors from "../../../config/colors";
import { Dimensions } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
const { height, width } = Dimensions.get("screen");

const CartWithHorizontalSlideStyle = StyleSheet.create({
     container: {
    flex: 1,
    backgroundColor: colors.backgroundSecondary,
    paddingBottom: height * 0.05,
  },
  amountToPay: {
    marginTop: hp("0.8%"),
    marginBottom: hp("0.4%"),
    fontFamily: "Poppins-SemiBold",
    fontSize: RFValue(12, 800),
    fontWeight: "700",
    textAlign: "center",
    color: colors.textHeading,
    letterSpacing: 0.3,
  },
  minimumCartAmountView: {
    backgroundColor: colors.error + "20",
    paddingVertical: hp("1%"),
    paddingHorizontal: wp("4%"),
    marginHorizontal: wp("4%"),
    marginBottom: hp("1%"),
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.error + "40",
  },
  miminumCartAmountText: {
    fontFamily: "Poppins-Medium",
    fontSize: RFValue(11, 800),
    fontWeight: "500",
    color: colors.error,
    textAlign: "center",
  },
  loadingOverlay: {
    width: wp("100%"),
    height: hp("100%"),
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  },
  listContainer: {
    paddingHorizontal: wp("4%"),
    paddingTop: hp("1%"),
    paddingBottom: height * 0.15,
  },
  itemSeparator: {
    height: hp("1%"),
  },
  cartItemContainer: {
    backgroundColor: colors.background,
    borderRadius: 12,
    flexDirection: "row",
    minHeight: hp("15%"),
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    overflow: "hidden",
    padding: wp("2.5%"),
  },
  imageContainer: {
    width: wp("18%"),
    height: wp("18%"),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 10,
    padding: wp("1%"),
    marginRight: wp("2.5%"),
  },
  productImage: {
    width: "100%",
    height: "100%",
    borderRadius: 6,
  },
  productDetailsContainer: {
    flex: 1,
    justifyContent: "space-between",
  },
  productInfo: {
    flex: 1,
  },
  productName: {
    fontSize: RFValue(13, 800),
    fontWeight: "700",
    color: colors.textHeading,
    lineHeight: RFValue(17, 800),
    marginBottom: hp("0.6%"),
    fontFamily: "Poppins-SemiBold",
  },
  unavailableContainer: {
    backgroundColor: colors.error + "15",
    paddingVertical: hp("0.4%"),
    paddingHorizontal: wp("1.5%"),
    borderRadius: 5,
    alignSelf: "flex-start",
    marginBottom: hp("0.6%"),
  },
  unavailableText: {
    fontSize: RFValue(9, 800),
    color: colors.error,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
    letterSpacing: 0.2,
  },
  productDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: hp("0.6%"),
  },
  priceSection: {
    flex: 1,
  },
  unitSection: {
    flex: 1,
    alignItems: "flex-end",
  },
  sectionLabel: {
    fontSize: RFValue(8, 800),
    fontWeight: "600",
    color: colors.textTertiary,
    marginBottom: hp("0.2%"),
    fontFamily: "Poppins-SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: hp("0.4%"),
  },
  priceLabel: {
    fontSize: RFValue(11, 800),
    fontWeight: "500",
    color: colors.textTertiary,
  },
  currentPrice: {
    fontSize: RFValue(12, 800),
    fontWeight: "700",
    color: colors.textHeading,
    fontFamily: "Poppins-Bold",
  },
  discountPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: wp("1.5%"),
  },
  discountedPrice: {
    fontSize: RFValue(12, 800),
    fontWeight: "700",
    color: colors.textHeading,
    fontFamily: "Poppins-Bold",
  },
  originalPrice: {
    fontSize: RFValue(10, 800),
    fontWeight: "500",
    color: colors.error,
    textDecorationLine: "line-through",
    fontFamily: "Poppins-Medium",
  },
  unitContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  unitLabel: {
    fontSize: RFValue(11, 800),
    fontWeight: "500",
    color: colors.textTertiary,
  },
  unitValue: {
    fontSize: RFValue(11, 800),
    fontWeight: "700",
    color: colors.textSecondary,
    fontFamily: "Poppins-Bold",
  },
  bottomSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: hp("0.8%"),
    paddingTop: hp("0.8%"),
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  totalPriceContainer: {
    flex: 1,
  },
  totalPrice: {
    fontSize: RFValue(16, 800),
    fontWeight: "700",
    color: colors.primary,
    fontFamily: "Poppins-Bold",
    letterSpacing: 0.3,
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 8,
    paddingVertical: hp("0.4%"),
    paddingHorizontal: wp("0.8%"),
    borderWidth: 1,
    borderColor: colors.border,
  },
  quantityButton: {
    width: wp("8%"),
    height: hp("3.5%"),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    backgroundColor: colors.background,
  },
  disabledButton: {
    opacity: 0.4,
    backgroundColor: colors.backgroundSecondary,
  },
  quantityButtonText: {
    fontSize: RFValue(18, 800),
    fontWeight: "700",
    color: colors.primary,
    fontFamily: "Poppins-Bold",
  },
  quantityDisplay: {
    minWidth: wp("10%"),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: wp("2%"),
  },
  quantityText: {
    fontSize: RFValue(14, 800),
    fontWeight: "700",
    color: colors.textHeading,
    textAlign: "center",
    fontFamily: "Poppins-Bold",
  },
  disabledButtonImage: {
    width: wp("4.5%"),
    height: wp("4.5%"),
    resizeMode: "contain",
    opacity: 0.5,
  },
  suggestionContainer: {
    backgroundColor: colors.background,
    borderRadius: 12,
    marginTop: hp("1.5%"),
    padding: wp("3%"),
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  emptyCartContainer: {
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    borderRadius: 20,
    width: wp("86%"),
    height: hp("70%"),
    padding: wp("6%"),
    marginTop: hp("2%"),
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
  },
  emptyCartImage: {
    resizeMode: "contain",
    width: wp("25%"),
    height: hp("12%"),
    marginBottom: hp("2.5%"),
    opacity: 0.8,
  },
  emptyCartTitle: {
    fontSize: RFValue(18, 800),
    fontWeight: "700",
    color: colors.textHeading,
    fontFamily: "Poppins-Bold",
    textAlign: "center",
    marginBottom: hp("0.8%"),
  },
  emptyCartSubtitle: {
    fontSize: RFValue(13, 800),
    fontWeight: "500",
    color: colors.textSecondary,
    fontFamily: "Poppins-Medium",
    textAlign: "center",
    marginBottom: hp("3%"),
  },
  startShoppingButton: {
    borderRadius: 12,
    backgroundColor: colors.buttonPrimary,
    paddingHorizontal: wp("7%"),
    paddingVertical: hp("0.8%"),
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.buttonPrimary,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  startShoppingGradient: {
    width: "100%",
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  startShoppingText: {
    color: colors.background,
    fontSize: RFValue(14, 800),
    fontFamily: "Poppins-Bold",
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  checkoutButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.background,
    paddingHorizontal: wp("4%"),
    paddingVertical: hp("1.5%"),
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
  },
  checkoutButton: {
    backgroundColor: colors.buttonPrimary,
    borderRadius: 12,
    paddingVertical: hp("1.6%"),
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.buttonPrimary,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  checkoutButtonText: {
    fontSize: RFValue(14, 800),
    fontWeight: "700",
    fontFamily: "Poppins-Bold",
    color: colors.background,
    letterSpacing: 0.5,
  },
  });

export default CartWithHorizontalSlideStyle;
