import { Platform, StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";

const CheckoutStyle = StyleSheet.create({
  Container: {
    backgroundColor: "#FFF",
    alignItems: "center",
    width: wp("100%"),
    height: "100%",
  },
  ScrollView: {
    backgroundColor: "#fff",
    paddingTop: hp("3.5%"),
    paddingBottom: hp("12%"),
  },
  inputContainer: {
    width: wp("100%"),
    alignItems: "center",
    marginTop: hp("3.375%"),
    height: hp("14.75%"),
  },
  label: {
    position: "absolute",
    top: -hp("1.5%"),
    left: wp("10%"),
    backgroundColor: "#FFFFFF",
    paddingHorizontal: wp("1.5%"),
    fontSize: RFValue(14),
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
    color: "#525252",
    zIndex: 1,
  },
  input: {
    width: wp("91.11%"),
    height: hp("14.75%"),
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    fontSize: RFValue(14),
    borderWidth: 1,
    borderColor: "#ccc",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  contentHeader: {
    width: wp("91.11%"),
    // marginHorizontal: 10,
    marginTop: hp("2.875%"),
    // backgroundColor: "#000",
    alignSelf: "center",
  },
  contentHeaderText: {
    fontSize: RFValue(16),
    fontWeight: "600",
    color: "#525252",
    fontFamily: "Poppins-SemiBold",
  },
  AddressView: {
    width: wp("91.11%"),
    height: hp("7.25%"),
    borderRadius: 10,
    alignSelf: "center",
    overflow: "hidden",
    // backgroundColor: "#000",
  },
  AddressTextView: {
    width: wp("91.11%"),
    height: hp("7.25%"),
    backgroundColor: "#DEECFA",
    justifyContent: "space-around",
    marginBottom: hp("1.875%"),
    flexDirection: "row",
    elevation: 5,
    shadowColor: "#B3B3B340",
  },
  paymentTypeText: {
    fontSize: RFValue(14),
    fontWeight: "600",
    textAlign: "left",
    color: "#525252",
    fontFamily: "Poppins-Medium",
    lineHeight: Platform.OS === "android" ? 14 : 0,
  },
  Voucher: {
    // marginHorizontal: wp("4.44%"),
    marginVertical: hp("2.875%"),
    marginBottom: hp("3.8%"),
    flexDirection: "row",
    width: wp("91.11%"),
    borderRadius: 10,
    height: hp("7.25%"),
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#ccc",
  },
  VoucherInput: {
    width: wp("63.11%"),
    height: hp("7%"),
    fontSize: RFValue(14),
    left: wp("4.44%"),
    // borderWidth: 1,
    // borderColor: "#ccc",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  VoucherButton: {
    width: wp("28%"),
    height: hp("7.25%"),
    backgroundColor: "#56a6ecff",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  VoucherButtonText: {
    fontSize: RFValue(14, 800),
    fontWeight: "600",
    textAlign: "center",
    color: "#FFFFFF",
    fontFamily: "Poppins-Medium",
  },
  paymentMethod: {
    backgroundColor: "#FFF",
    marginVertical: hp("0.88%"),
    width: wp("91.11%"),
    alignSelf: "center",
    borderRadius: 15,
    flexDirection: "column",
  },
  paymentSection: {
    backgroundColor: "#000",
    // marginVertical: 7,
    width: "89%",
    //  height: 185,
    alignSelf: "center",
    borderRadius: 15,
    flexDirection: "column",
  },
  AmountView: {
    //  backgroundColor: "green",
    width: "100%",
    height: "100%",
    borderRadius: 15,
    alignSelf: "center",
    // marginTop: 8,
    paddingTop: 15,
    overflow: "hidden",
  },
  deliverySelectionView: {
    width: wp("13.6665%"),
    height: hp("7.25%"),
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "green",
  },
  deliverySelectionButton: {
    resizeMode: "contain",
    width: wp("6.67%"),
    height: hp("3%"),
  },
  deliveryTypeName: {
    width: wp("78%"),
    height: hp("7.25%"),
    borderRadius: 15,
    justifyContent: "center",
    // backgroundColor: "red",
  },
  TextView: {
    // marginTop:15,
    justifyContent: "space-between",
    flexDirection: "row",
    // borderBottomColor: "red",
    // backgroundColor : 'white',
    // borderBottomWidth: 1,
    paddingHorizontal: 20,
  },
  Text: {
    fontSize: 20,
    fontWeight: 500,
    textAlign: "center",
    color: "#133051",
    lineHeight: 44,
  },
  ButtonView: {
    backgroundColor: "#58BB47",
    width: "89%",
    height: "6.5%",
    alignSelf: "center",
    position: "absolute",
    bottom: 40,
    borderRadius: 20,
    justifyContent: "center",
  },
  buttonText: {
    textAlign: "center",
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: 500,
  },
  quantityTouchable: {
    backgroundColor: "#fff",
    position: "absolute",
    width: wp("91.11%"),
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    alignSelf: "center",
    bottom: hp("8%"),
    borderRadius: 10,
    // zIndex:1,
    //  marginBottom:70
  },
  gradientButton: {
    width: wp("91.11%"),
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    // marginTop: 20,
    overflow: "hidden",
  },
  addToCartButton: {
    width: wp("91.11%"),
    height: hp("6%"),
    alignItems: "center",
    justifyContent: "center",
    // paddingHorizontal: 26,
    // marginBottom: 7,
    borderRadius: 10,
    // backgroundColor: colors.green,
  },
  addToCartText: {
    color: "#ffffff",
    fontSize: RFValue(14),
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
});

export default CheckoutStyle;
