import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import colors from "../../../config/colors";
import { RFValue } from "react-native-responsive-fontsize";

const productListingStyle = StyleSheet.create({
  selectedCat: {
    backgroundColor: "#F4F9FF",
    borderRadius: 10,
    shadowColor: "#E4E4E4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    paddingHorizontal: wp("3.89%"),
  },
  selectedCatText: {
    color:"#525252",
    fontSize: RFValue(12),
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },

  gradient: {
    flex: 1,
    width: wp("100%"),
    height: hp("100%"),
    alignSelf: "center",
  },
  catListCommonView: {
    backgroundColor: "#FFFFFF",
    width: wp("100%"),
    height: hp("6%"),
    marginTop: hp("0.875%"),
    marginBottom: hp("0.25%"),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    elevation: 3,
    shadowColor: "#A3A3A340",
  },
  filterIcon: {
    width: wp("9.72%"),
    height: hp("3.75%"),
    resizeMode: "contain",
    // borderRadius: wp('2%'),
    alignItems: "center",
    justifyContent: "center",
    marginLeft: wp("4.44%"),
    marginRight: wp("1.39%"),
  },
  catListView: {
    backgroundColor: "white",
    // width: "20%",
    height: hp("3.75%"),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: wp("3.89%"),
    marginRight: wp("1.39%"),
    borderRadius: 10,
    // elevation: 5,
    borderColor: "#E4E4E4",
    borderWidth: wp("0.28%"),
  },
  catText: {
    color:"#525252",
    fontFamily: "Poppins-Medium",
    fontSize: RFValue(12),
    fontWeight: "500",
  },
  container: {
    flex: 1,
    width: wp("100%"),
    alignItems: "flex-start",
    justifyContent: "flex-start",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  flatList: {
    width: wp("91.11%"),
    // flexDirection:"row",
    alignItems: "flex-start",
    overflow: "hidden",
    paddingBottom: hp("20%"),
    // marginBottom: hp("50%"),
    // backgroundColor: "#000",
  },
  flatList2: {
    //  width: wp("100%"),
    height: hp("6%"),
    // backgroundColor: "#000",
    paddingRight: wp("4%"),
    alignItems: "center",
    // justifyContent: "center",
    alignSelf: "center",
  },
  widget: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: wp("0.625%"),
    marginVertical: hp("0.625%"),
    width: wp("45%"),
    borderRadius: 12,
    elevation: 5,
    alignItems: "center",
    shadowColor: "#A3A3A340",
    overflow: "hidden",
    paddingBottom: 10, // Add some padding at the bottom
  },
  imageTouchView: {
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    height: hp("22%"),
    width: wp("45%"),
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
    wishListButton: {
    position: "absolute",
    top: hp("1%"),
    right: wp("3%"),
    zIndex: 2,
  },
  wishicon: {
    resizeMode: "contain",
    width: wp("6%"),
    height: wp("6%"),
  },
  images: {
    height: hp("20%"),
    width: wp("45%"),
    resizeMode: "contain",
    // backgroundColor: "#000",
  },
  imagePlaceholder: {
    height: 185,
    width: 180,
    backgroundColor: "#F4F9FF",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
  placeholderText: {
    color: "#666",
    fontSize: 14,
  },
  textView: {
    // backgroundColor: "green",
    width: wp("45%"),
    paddingHorizontal: wp("4.44%"),
    paddingTop: hp("1%"),
    // paddingBottom: hp("0.5%"),
    minHeight: hp("9%"),
    justifyContent: "flex-start",
  },
  ProductNameView: {
    // height: hp("11%"),
    // backgroundColor: "blue",
    justifyContent: "center",
  },
  productNameContainer: {
    height: RFValue(54, 800), // Fixed height for 2 lines (19 * 2)
    justifyContent: 'flex-start',
    marginBottom: hp("0.5%"),
  },
  ProductName: {
    textAlign: "left",
    fontSize: RFValue(14, 800),
    fontWeight: "500",
    color: "#525252",
    fontFamily: "Poppins-Medium",
    lineHeight: RFValue(19, 800),
    maxHeight: RFValue(57, 800), // 3 lines (19 * 3)
    overflow: 'hidden',
  },
  PriceCommonView: {
    // backgroundColor:"#1AD",
    flexDirection: "row",
    alignItems: "baseline",
    alignSelf: "baseline",
    // top: 5,
  },
  PriceView: {
    // height: 30,
    justifyContent: "center",
  },
  AedText: {
    fontSize: RFValue(14, 800),
    // marginVertical: hp("1%"),
    // marginVertical: hp("1%"),
    textAlign: "left",
    fontWeight: "600",
    color: "#525252",
    fontFamily: "Poppins-SemiBold",
  },
  ProductPrice: {
    // alignItems: "center",
    textAlign: "left",
    color: "#525252",
    fontSize: RFValue(14, 800),
    fontWeight: "600",
    // left: 5,
  },
  commonView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 30,
  },
  oldPriceView: {
    flex: 1,
  },
  oldProductPrice: {
    fontSize: 14,
    textDecorationLine: "line-through",
    color: "#FE5656",
  },
  quantitySection: {
    width: 80,
    alignItems: "flex-end",
  },
  addButton: {
    width: 27,
    height: 27,
    resizeMode: "contain",
  },
  errorContainer: {
    padding: 10,
    alignItems: "center",
    width: "100%",
  },
  errorText: {
    color: "#FE5656",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 5,
  },
  retryButton: {
    padding: 8,
    backgroundColor: colors.primary,
    borderRadius: 5,
    minWidth: 100,
    alignItems: "center",
  },
  retryText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  emptyContainer: {
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    width: "100%",
    paddingTop: hp("20%"),
  },
  noProductsImage:{
    width: wp('45.28%'),
    height:  wp("45.28%"),
    resizeMode: "contain",
    alignItems: "center",
    justifyContent: "center",
  },
  noProductsText: {
    fontSize: RFValue(14),
    marginTop: hp('2%'),
    color: "#525252",
    fontWeight: "500",
    textAlign: "center",
    fontFamily: "Poppins-Medium",
    overflow: "hidden",
  },
  loadingContainer: {
    width: wp("100%"),
    paddingVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf:"center"
  },
  loadingText: {
    marginTop: 10,
    color: "#B4B4B4",
    fontSize: RFValue(14,800),
  },
  quantityTouchable: {
    width: "100%",
    height: hp("6%"),
    alignItems: "center",
  },
  gradientButton: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    overflow: "hidden",
  },
  addToCartButton: {
    width: "85%",
    // height: "80%",
    aspectRatio: 4,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    // marginBottom: hp("-4%"),
    // backgroundColor: colors.green,
  },
  addToCartText: {
    // backgroundColor: "blue",
    color: "white",
    fontSize: RFValue(14, 800),
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
});

export default productListingStyle;
